package com.forgenet.client;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.util.Base64;import android.view.*;import android.widget.*;
import java.io.*;import java.math.BigInteger;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.SecureRandom;import java.util.*;import org.json.*;

public class MainActivity extends Activity {
  EditText server,token,name,endpoint; TextView status; Button enroll,sync,share; android.content.SharedPreferences prefs;
  public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("forgenet",MODE_PRIVATE);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);int space=dp(20);root.setPadding(space,space,space,space);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.addView(root,new ScrollView.LayoutParams(-1,-2));scroll.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(space,space+insets.getSystemWindowInsetTop(),space,space+insets.getSystemWindowInsetBottom());return insets;});TextView title=new TextView(this);title.setText("ForgeNet");title.setTextSize(30);title.setTextColor(Color.rgb(0,90,110));root.addView(title);root.addView(label("Self-hosted WireGuard network client\n"));server=input(root,"Server URL (HTTPS)",prefs.getString("server","https://network.example.com"));token=input(root,"Enrollment token","");name=input(root,"Device name",Build.MODEL.replace(' ','-'));endpoint=input(root,"Public endpoint (optional)","");enroll=button(root,"Enroll this phone");sync=button(root,"Sync peers");share=button(root,"Share WireGuard configuration");status=label("Ready. Install the official WireGuard app before importing the generated configuration.");status.setTextIsSelectable(true);root.addView(status);setContentView(scroll);enroll.setOnClickListener(v->background(()->doEnroll()));sync.setOnClickListener(v->background(()->doSync()));share.setOnClickListener(v->shareConfig());}
  int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);} TextView label(String s){TextView v=new TextView(this);v.setId(View.generateViewId());v.setText(s);v.setTextSize(16);v.setPadding(0,dp(8),0,dp(12));return v;} EditText input(LinearLayout p,String hint,String value){EditText e=new EditText(this);e.setId(View.generateViewId());e.setHint(hint);e.setText(value);e.setTextSize(16);e.setSingleLine(true);e.setMinHeight(dp(48));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(6));p.addView(e,lp);return e;} Button button(LinearLayout p,String s){Button b=new Button(this);b.setId(View.generateViewId());b.setText(s);b.setMinHeight(dp(48));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));p.addView(b,lp);return b;}
  void background(Task t){setBusy(true);new Thread(()->{try{t.run();}catch(Exception e){show("ERROR: "+e.getMessage());}finally{runOnUiThread(()->setBusy(false));}}).start();} interface Task{void run()throws Exception;} void setBusy(boolean x){enroll.setEnabled(!x);sync.setEnabled(!x);share.setEnabled(!x);} void show(String x){runOnUiThread(()->status.setText(x));}
  URL url(String path)throws Exception{URL u=new URL(server.getText().toString().trim().replaceAll("/$","")+path);if(!u.getProtocol().equals("https"))throw new Exception("ForgeNet requires an HTTPS server on Android.");return u;}
  JSONObject post(String path,JSONObject body,String id,String secret)throws Exception{HttpURLConnection c=(HttpURLConnection)url(path).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");if(secret!=null){c.setRequestProperty("Authorization","Bearer "+secret);c.setRequestProperty("X-ForgeNet-Device",id);}c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();String text=read(in);JSONObject out=new JSONObject(text);if(code>=400)throw new Exception(out.optString("error","Server request failed"));return out;}
  void doEnroll()throws Exception{byte[] priv=new byte[32];new SecureRandom().nextBytes(priv);priv[0]&=248;priv[31]&=127;priv[31]|=64;byte[] pub=x25519(priv);JSONObject req=new JSONObject().put("token",token.getText().toString().trim()).put("name",name.getText().toString().trim()).put("publicKey",b64(pub)).put("endpoint",endpoint.getText().length()==0?JSONObject.NULL:endpoint.getText().toString().trim());JSONObject out=post("/v1/devices/enroll",req,null,null),d=out.getJSONObject("device");prefs.edit().putString("server",server.getText().toString().trim().replaceAll("/$","")).putString("id",d.getString("id")).putString("secret",out.getString("secret")).putString("private",b64(priv)).putString("ip",d.getString("ip")).apply();runOnUiThread(()->token.setText(""));show("Enrolled as "+d.getString("ip")+". Tap Sync peers.");}
  void doSync()throws Exception{String id=prefs.getString("id","");if(id.length()==0)throw new Exception("Enroll this phone first.");JSONObject req=new JSONObject().put("endpoint",endpoint.getText().length()==0?JSONObject.NULL:endpoint.getText().toString().trim());JSONObject out=post("/v1/devices/heartbeat",req,id,prefs.getString("secret",null));StringBuilder c=new StringBuilder("[Interface]\nPrivateKey = ").append(prefs.getString("private","")).append("\nAddress = ").append(out.getJSONObject("device").getString("ip")).append("/32\nListenPort = 51820\n");JSONArray peers=out.getJSONArray("peers");int active=0;for(int i=0;i<peers.length();i++){JSONObject p=peers.getJSONObject(i);if(p.isNull("endpoint"))continue;active++;c.append("\n[Peer]\nPublicKey = ").append(p.getString("publicKey")).append("\nAllowedIPs = ").append(p.getString("ip")).append("/32\nEndpoint = ").append(p.getString("endpoint")).append("\nPersistentKeepalive = 25\n");}prefs.edit().putString("config",c.toString()).apply();show("Configuration ready with "+active+" reachable peer(s). Tap Share and import it into WireGuard.");}
  void shareConfig(){String c=prefs.getString("config","");if(c.length()==0){show("Sync peers first.");return;}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"ForgeNet.conf");i.putExtra(Intent.EXTRA_TEXT,c);startActivity(Intent.createChooser(i,"Import or save ForgeNet configuration"));}
  static String read(InputStream in)throws Exception{if(in==null)return "{}";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] x=new byte[4096];for(int n;(n=in.read(x))>0;)b.write(x,0,n);return b.toString("UTF-8");}static String b64(byte[] x){return Base64.encodeToString(x,Base64.NO_WRAP);}
  static byte[] x25519(byte[] k){BigInteger p=BigInteger.ONE.shiftLeft(255).subtract(BigInteger.valueOf(19)),x1=BigInteger.valueOf(9),x2=BigInteger.ONE,z2=BigInteger.ZERO,x3=x1,z3=BigInteger.ONE;int swap=0;for(int pos=254;pos>=0;pos--){int bit=(k[pos>>3]>>(pos&7))&1;swap^=bit;if(swap!=0){BigInteger t=x2;x2=x3;x3=t;t=z2;z2=z3;z3=t;}swap=bit;BigInteger a=x2.add(z2).mod(p),aa=a.multiply(a).mod(p),bb=x2.subtract(z2).mod(p);bb=bb.multiply(bb).mod(p);BigInteger e=aa.subtract(bb).mod(p),cc=x3.add(z3).mod(p),d=x3.subtract(z3).mod(p),da=d.multiply(a).mod(p),cb=cc.multiply(x2.subtract(z2).mod(p)).mod(p);x3=da.add(cb).mod(p);x3=x3.multiply(x3).mod(p);z3=da.subtract(cb).mod(p);z3=x1.multiply(z3.multiply(z3).mod(p)).mod(p);x2=aa.multiply(bb).mod(p);z2=e.multiply(aa.add(BigInteger.valueOf(121665).multiply(e)).mod(p)).mod(p);}if(swap!=0){BigInteger t=x2;x2=x3;x3=t;t=z2;z2=z3;z3=t;}BigInteger r=x2.multiply(z2.modInverse(p)).mod(p);byte[] out=new byte[32],be=r.toByteArray();for(int i=0;i<be.length&&i<32;i++)out[i]=be[be.length-1-i];return out;}
}
